### PR TITLE
Enable handler_invoke_parallel_for_with_range_size_t for DPCPP

### PR DESCRIPTION
**Pull request by dm-vodopyanov**
This patch should be merged after 

- https://github.com/intel/llvm/pull/10660 

is merged.

### CODE REVIEW

**Review by bader — APPROVED** [review]

**Comment by dm-vodopyanov** [comment]
@bader can you please re-run the checks and merge this patch, as the patch with implementation was merged to intel/llvm?

**Comment by bader** [comment]
@dm-vodopyanov, I can't test this PR due to a regression with new DPC++ compiler.
See https://github.com/KhronosGroup/SYCL-CTS/actions/runs/5765388447/job/15631290975
```
/opt/sycl/bin/../include/sycl/types.hpp:1271:16: error: invalid argument type 'const DataType' (aka 'const std::array<double, 16>') to unary expression
 1271 |     return vec{+m_Data};
      |                ^~~~~~~
/__w/SYCL-CTS/SYCL-CTS/build/tests/vector_operators/vector_operators_double.cpp:2651:14: note: in instantiation of member function 'sycl::vec<double, 16>::operator+' requested here
 2651 |     resVec = +testVec1;
      |              ^
```
Could you fix this regression, please?

**Comment by dm-vodopyanov** [comment]
> @dm-vodopyanov, I can't test this PR due to a regression with new DPC++ compiler. See https://github.com/KhronosGroup/SYCL-CTS/actions/runs/5765388447/job/15631290975
> 
> ```
> /opt/sycl/bin/../include/sycl/types.hpp:1271:16: error: invalid argument type 'const DataType' (aka 'const std::array<double, 16>') to unary expression
>  1271 |     return vec{+m_Data};
>       |                ^~~~~~~
> /__w/SYCL-CTS/SYCL-CTS/build/tests/vector_operators/vector_operators_double.cpp:2651:14: note: in instantiation of member function 'sycl::vec<double, 16>::operator+' requested here
>  2651 |     resVec = +testVec1;
>       |              ^
> ```
> 
> Could you fix this regression, please?

Found an internal high exposure ticket on that, it was assigned to @cperkinsintel (guilty commit: https://github.com/intel/llvm/pull/9492)

@cperkinsintel can you please prioritize? It blocks the update of DPC++ compiler for SYCL CTS testing.

**Comment by cperkinsintel** [comment]
PR for unary ops fix on SYCL here: https://github.com/intel/llvm/pull/10722
